import { createContext, useContext } from "react";
import { useCurrentWeather, WeatherProps } from "../hooks/useCurrentWeather";

const CurrWeatherContext = createContext<WeatherProps>({
  currentWeather: null,
  loading: true,
  error: undefined,
});

export function useCurrWeather() {
  const context = useContext(CurrWeatherContext);
  if (context === undefined) {
    throw new Error("useCurrWeather must be used within a CurrWeatherProvider");
  }
  return context;
}

const currWeather: WeatherProps = {
  currentWeather: {
    location: {
      name: "Nangloi Jat",
      region: "",
      country: "India",
      lat: 28.68,
      lon: 77.07,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1675964876,
      localtime: "2023-02-09 23:17",
    },
    current: {
      last_updated_epoch: 1675964700,
      last_updated: "2023-02-09 23:15",
      temp_c: 19,
      temp_f: 66.2,
      is_day: 0,
      condition: {
        text: "Mist",
        icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
        code: 1030,
      },
      wind_mph: 5.6,
      wind_kph: 9,
      wind_degree: 90,
      wind_dir: "E",
      pressure_mb: 1012,
      pressure_in: 29.88,
      precip_mm: 0,
      precip_in: 0,
      humidity: 68,
      cloud: 0,
      feelslike_c: 19,
      feelslike_f: 66.2,
      vis_km: 3.5,
      vis_miles: 2,
      uv: 1,
      gust_mph: 15,
      gust_kph: 24.1,
      air_quality: {
        co: 2056.10009765625,
        no2: 69.19999694824219,
        o3: 32.900001525878906,
        so2: 40.099998474121094,
        pm2_5: 179.3000030517578,
        pm10: 225.10000610351562,
        "us-epa-index": 5,
        "gb-defra-index": 10,
      },
    },
    forecast: {
      forecastday: [
        {
          date: "2023-02-09",
          date_epoch: 1675900800,
          day: {
            maxtemp_c: 29.8,
            maxtemp_f: 85.6,
            mintemp_c: 13.5,
            mintemp_f: 56.3,
            avgtemp_c: 20.4,
            avgtemp_f: 68.7,
            maxwind_mph: 7.2,
            maxwind_kph: 11.5,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 32,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "07:05 AM",
            sunset: "06:07 PM",
            moonrise: "09:20 PM",
            moonset: "09:10 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "91",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1675881000,
              time: "2023-02-09 00:00",
              temp_c: 15.2,
              temp_f: 59.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 297,
              wind_dir: "WNW",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              humidity: 36,
              cloud: 0,
              feelslike_c: 15.2,
              feelslike_f: 59.4,
              windchill_c: 15.2,
              windchill_f: 59.4,
              heatindex_c: 15.2,
              heatindex_f: 59.4,
              dewpoint_c: 0.4,
              dewpoint_f: 32.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 1,
            },
            {
              time_epoch: 1675884600,
              time: "2023-02-09 01:00",
              temp_c: 14.8,
              temp_f: 58.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 300,
              wind_dir: "WNW",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 14.6,
              feelslike_f: 58.3,
              windchill_c: 14.6,
              windchill_f: 58.3,
              heatindex_c: 14.8,
              heatindex_f: 58.6,
              dewpoint_c: 0.1,
              dewpoint_f: 32.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1675888200,
              time: "2023-02-09 02:00",
              temp_c: 14.4,
              temp_f: 57.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 316,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 38,
              cloud: 0,
              feelslike_c: 14.2,
              feelslike_f: 57.6,
              windchill_c: 14.2,
              windchill_f: 57.6,
              heatindex_c: 14.4,
              heatindex_f: 57.9,
              dewpoint_c: 0.2,
              dewpoint_f: 32.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1675891800,
              time: "2023-02-09 03:00",
              temp_c: 14,
              temp_f: 57.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 322,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 0,
              feelslike_c: 13.8,
              feelslike_f: 56.8,
              windchill_c: 13.8,
              windchill_f: 56.8,
              heatindex_c: 14,
              heatindex_f: 57.2,
              dewpoint_c: -0.4,
              dewpoint_f: 31.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1675895400,
              time: "2023-02-09 04:00",
              temp_c: 13.9,
              temp_f: 57,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 319,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 35,
              cloud: 0,
              feelslike_c: 13.7,
              feelslike_f: 56.7,
              windchill_c: 13.7,
              windchill_f: 56.7,
              heatindex_c: 13.9,
              heatindex_f: 57,
              dewpoint_c: -1.1,
              dewpoint_f: 30,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1,
            },
            {
              time_epoch: 1675899000,
              time: "2023-02-09 05:00",
              temp_c: 13.7,
              temp_f: 56.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 13.6,
              feelslike_f: 56.5,
              windchill_c: 13.6,
              windchill_f: 56.5,
              heatindex_c: 13.7,
              heatindex_f: 56.7,
              dewpoint_c: -1.7,
              dewpoint_f: 28.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
            {
              time_epoch: 1675902600,
              time: "2023-02-09 06:00",
              temp_c: 13.5,
              temp_f: 56.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 3,
              feelslike_c: 13.4,
              feelslike_f: 56.1,
              windchill_c: 13.4,
              windchill_f: 56.1,
              heatindex_c: 13.5,
              heatindex_f: 56.3,
              dewpoint_c: -2.1,
              dewpoint_f: 28.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
            {
              time_epoch: 1675906200,
              time: "2023-02-09 07:00",
              temp_c: 13.7,
              temp_f: 56.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 265,
              wind_dir: "W",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 4,
              feelslike_c: 13.6,
              feelslike_f: 56.5,
              windchill_c: 13.6,
              windchill_f: 56.5,
              heatindex_c: 13.7,
              heatindex_f: 56.7,
              dewpoint_c: -1.8,
              dewpoint_f: 28.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 4,
            },
            {
              time_epoch: 1675909800,
              time: "2023-02-09 08:00",
              temp_c: 15.8,
              temp_f: 60.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 261,
              wind_dir: "W",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 4,
              feelslike_c: 15.8,
              feelslike_f: 60.4,
              windchill_c: 15.8,
              windchill_f: 60.4,
              heatindex_c: 15.8,
              heatindex_f: 60.4,
              dewpoint_c: 0.1,
              dewpoint_f: 32.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 5,
            },
            {
              time_epoch: 1675913400,
              time: "2023-02-09 09:00",
              temp_c: 18.6,
              temp_f: 65.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.4,
              wind_kph: 5.4,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 29,
              cloud: 3,
              feelslike_c: 18.6,
              feelslike_f: 65.5,
              windchill_c: 18.6,
              windchill_f: 65.5,
              heatindex_c: 18.6,
              heatindex_f: 65.5,
              dewpoint_c: 0.3,
              dewpoint_f: 32.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.5,
              gust_kph: 7.2,
              uv: 5,
            },
            {
              time_epoch: 1675917000,
              time: "2023-02-09 10:00",
              temp_c: 21.1,
              temp_f: 70,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 233,
              wind_dir: "SW",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 26,
              cloud: 2,
              feelslike_c: 21.1,
              feelslike_f: 70,
              windchill_c: 21.1,
              windchill_f: 70,
              heatindex_c: 22.5,
              heatindex_f: 72.5,
              dewpoint_c: 1,
              dewpoint_f: 33.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.5,
              gust_kph: 7.2,
              uv: 6,
            },
            {
              time_epoch: 1675920600,
              time: "2023-02-09 11:00",
              temp_c: 25.1,
              temp_f: 77.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 229,
              wind_dir: "SW",
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              humidity: 24,
              cloud: 2,
              feelslike_c: 24.3,
              feelslike_f: 75.7,
              windchill_c: 25.1,
              windchill_f: 77.2,
              heatindex_c: 24.3,
              heatindex_f: 75.7,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.9,
              gust_kph: 7.9,
              uv: 7,
            },
            {
              time_epoch: 1675924200,
              time: "2023-02-09 12:00",
              temp_c: 26.1,
              temp_f: 79,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 229,
              wind_dir: "SW",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 23,
              cloud: 3,
              feelslike_c: 24.9,
              feelslike_f: 76.8,
              windchill_c: 26.1,
              windchill_f: 79,
              heatindex_c: 24.9,
              heatindex_f: 76.8,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.1,
              gust_kph: 8.3,
              uv: 7,
            },
            {
              time_epoch: 1675927800,
              time: "2023-02-09 13:00",
              temp_c: 29.1,
              temp_f: 84.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 238,
              wind_dir: "WSW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 23,
              cloud: 5,
              feelslike_c: 27.3,
              feelslike_f: 81.1,
              windchill_c: 29.1,
              windchill_f: 84.4,
              heatindex_c: 27.3,
              heatindex_f: 81.1,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 7,
            },
            {
              time_epoch: 1675931400,
              time: "2023-02-09 14:00",
              temp_c: 29.7,
              temp_f: 85.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 240,
              wind_dir: "WSW",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 23,
              cloud: 4,
              feelslike_c: 27.8,
              feelslike_f: 82,
              windchill_c: 29.7,
              windchill_f: 85.5,
              heatindex_c: 27.8,
              heatindex_f: 82,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 7,
            },
            {
              time_epoch: 1675935000,
              time: "2023-02-09 15:00",
              temp_c: 29.8,
              temp_f: 85.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 245,
              wind_dir: "WSW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 23,
              cloud: 5,
              feelslike_c: 27.9,
              feelslike_f: 82.2,
              windchill_c: 29.8,
              windchill_f: 85.6,
              heatindex_c: 27.9,
              heatindex_f: 82.2,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 7,
            },
            {
              time_epoch: 1675938600,
              time: "2023-02-09 16:00",
              temp_c: 29.5,
              temp_f: 85.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 2.9,
              wind_kph: 4.7,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 27,
              cloud: 5,
              feelslike_c: 28,
              feelslike_f: 82.4,
              windchill_c: 29.5,
              windchill_f: 85.1,
              heatindex_c: 28,
              heatindex_f: 82.4,
              dewpoint_c: 8.4,
              dewpoint_f: 47.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 3.4,
              gust_kph: 5.4,
              uv: 7,
            },
            {
              time_epoch: 1675942200,
              time: "2023-02-09 17:00",
              temp_c: 26.2,
              temp_f: 79.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 1.6,
              wind_kph: 2.5,
              wind_degree: 48,
              wind_dir: "NE",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 32,
              cloud: 5,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 26.2,
              windchill_f: 79.2,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 8,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 2,
              gust_kph: 3.2,
              uv: 7,
            },
            {
              time_epoch: 1675945800,
              time: "2023-02-09 18:00",
              temp_c: 23.8,
              temp_f: 74.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 68,
              wind_dir: "ENE",
              pressure_mb: 1011,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 33,
              cloud: 4,
              feelslike_c: 24.3,
              feelslike_f: 75.7,
              windchill_c: 23.8,
              windchill_f: 74.8,
              heatindex_c: 24.3,
              heatindex_f: 75.7,
              dewpoint_c: 6.7,
              dewpoint_f: 44.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.8,
              gust_kph: 12.6,
              uv: 1,
            },
            {
              time_epoch: 1675949400,
              time: "2023-02-09 19:00",
              temp_c: 22.6,
              temp_f: 72.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 92,
              wind_dir: "E",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 35,
              cloud: 4,
              feelslike_c: 23.9,
              feelslike_f: 75,
              windchill_c: 22.6,
              windchill_f: 72.7,
              heatindex_c: 23.9,
              heatindex_f: 75,
              dewpoint_c: 6.5,
              dewpoint_f: 43.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1675953000,
              time: "2023-02-09 20:00",
              temp_c: 20.5,
              temp_f: 68.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 106,
              wind_dir: "ESE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 4,
              feelslike_c: 20.5,
              feelslike_f: 68.9,
              windchill_c: 20.5,
              windchill_f: 68.9,
              heatindex_c: 20.5,
              heatindex_f: 68.9,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
            {
              time_epoch: 1675956600,
              time: "2023-02-09 21:00",
              temp_c: 20,
              temp_f: 68,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 116,
              wind_dir: "ESE",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 4,
              feelslike_c: 20,
              feelslike_f: 68,
              windchill_c: 20,
              windchill_f: 68,
              heatindex_c: 20,
              heatindex_f: 68,
              dewpoint_c: 5,
              dewpoint_f: 41,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1675960200,
              time: "2023-02-09 22:00",
              temp_c: 19.6,
              temp_f: 67.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 126,
              wind_dir: "SE",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 4,
              feelslike_c: 19.6,
              feelslike_f: 67.3,
              windchill_c: 19.6,
              windchill_f: 67.3,
              heatindex_c: 19.6,
              heatindex_f: 67.3,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1675963800,
              time: "2023-02-09 23:00",
              temp_c: 19.1,
              temp_f: 66.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 124,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 40,
              cloud: 4,
              feelslike_c: 19.1,
              feelslike_f: 66.4,
              windchill_c: 19.1,
              windchill_f: 66.4,
              heatindex_c: 19.1,
              heatindex_f: 66.4,
              dewpoint_c: 5.1,
              dewpoint_f: 41.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.1,
              uv: 1,
            },
          ],
        },
        {
          date: "2023-02-10",
          date_epoch: 1675987200,
          day: {
            maxtemp_c: 30.7,
            maxtemp_f: 87.3,
            mintemp_c: 15.9,
            mintemp_f: 60.6,
            avgtemp_c: 22.2,
            avgtemp_f: 71.9,
            maxwind_mph: 8.5,
            maxwind_kph: 13.7,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 39,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "07:05 AM",
            sunset: "06:08 PM",
            moonrise: "10:14 PM",
            moonset: "09:37 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "84",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1675967400,
              time: "2023-02-10 00:00",
              temp_c: 18.5,
              temp_f: 65.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 124,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 3,
              feelslike_c: 18.5,
              feelslike_f: 65.3,
              windchill_c: 18.5,
              windchill_f: 65.3,
              heatindex_c: 18.5,
              heatindex_f: 65.3,
              dewpoint_c: 4.9,
              dewpoint_f: 40.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1675971000,
              time: "2023-02-10 01:00",
              temp_c: 17.9,
              temp_f: 64.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 129,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 4,
              feelslike_c: 17.9,
              feelslike_f: 64.2,
              windchill_c: 17.9,
              windchill_f: 64.2,
              heatindex_c: 17.9,
              heatindex_f: 64.2,
              dewpoint_c: 4.8,
              dewpoint_f: 40.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1675974600,
              time: "2023-02-10 02:00",
              temp_c: 17.4,
              temp_f: 63.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 131,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 43,
              cloud: 4,
              feelslike_c: 17.4,
              feelslike_f: 63.3,
              windchill_c: 17.4,
              windchill_f: 63.3,
              heatindex_c: 17.4,
              heatindex_f: 63.3,
              dewpoint_c: 4.7,
              dewpoint_f: 40.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
            {
              time_epoch: 1675978200,
              time: "2023-02-10 03:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 130,
              wind_dir: "SE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 4,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 4.6,
              dewpoint_f: 40.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 1,
            },
            {
              time_epoch: 1675981800,
              time: "2023-02-10 04:00",
              temp_c: 16.6,
              temp_f: 61.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 134,
              wind_dir: "SE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 4,
              feelslike_c: 16.6,
              feelslike_f: 61.9,
              windchill_c: 16.6,
              windchill_f: 61.9,
              heatindex_c: 16.6,
              heatindex_f: 61.9,
              dewpoint_c: 4.4,
              dewpoint_f: 39.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1675985400,
              time: "2023-02-10 05:00",
              temp_c: 16.2,
              temp_f: 61.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 139,
              wind_dir: "SE",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 5,
              feelslike_c: 16.2,
              feelslike_f: 61.2,
              windchill_c: 16.2,
              windchill_f: 61.2,
              heatindex_c: 16.2,
              heatindex_f: 61.2,
              dewpoint_c: 4,
              dewpoint_f: 39.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
            {
              time_epoch: 1675989000,
              time: "2023-02-10 06:00",
              temp_c: 15.9,
              temp_f: 60.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 141,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 44,
              cloud: 6,
              feelslike_c: 15.9,
              feelslike_f: 60.6,
              windchill_c: 15.9,
              windchill_f: 60.6,
              heatindex_c: 15.9,
              heatindex_f: 60.6,
              dewpoint_c: 3.8,
              dewpoint_f: 38.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.6,
              gust_kph: 22,
              uv: 1,
            },
            {
              time_epoch: 1675992600,
              time: "2023-02-10 07:00",
              temp_c: 15.9,
              temp_f: 60.6,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 144,
              wind_dir: "SE",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 7,
              feelslike_c: 15.9,
              feelslike_f: 60.6,
              windchill_c: 15.9,
              windchill_f: 60.6,
              heatindex_c: 15.9,
              heatindex_f: 60.6,
              dewpoint_c: 4,
              dewpoint_f: 39.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 5,
            },
            {
              time_epoch: 1675996200,
              time: "2023-02-10 08:00",
              temp_c: 17.4,
              temp_f: 63.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 148,
              wind_dir: "SSE",
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              humidity: 43,
              cloud: 7,
              feelslike_c: 17.4,
              feelslike_f: 63.3,
              windchill_c: 17.4,
              windchill_f: 63.3,
              heatindex_c: 17.4,
              heatindex_f: 63.3,
              dewpoint_c: 4.8,
              dewpoint_f: 40.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 5,
            },
            {
              time_epoch: 1675999800,
              time: "2023-02-10 09:00",
              temp_c: 19.9,
              temp_f: 67.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 161,
              wind_dir: "SSE",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 7,
              feelslike_c: 19.9,
              feelslike_f: 67.8,
              windchill_c: 19.9,
              windchill_f: 67.8,
              heatindex_c: 19.9,
              heatindex_f: 67.8,
              dewpoint_c: 4.7,
              dewpoint_f: 40.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 5,
            },
            {
              time_epoch: 1676003400,
              time: "2023-02-10 10:00",
              temp_c: 22.3,
              temp_f: 72.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 165,
              wind_dir: "SSE",
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 33,
              cloud: 6,
              feelslike_c: 23.6,
              feelslike_f: 74.5,
              windchill_c: 22.3,
              windchill_f: 72.1,
              heatindex_c: 23.6,
              heatindex_f: 74.5,
              dewpoint_c: 5.3,
              dewpoint_f: 41.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14,
              uv: 6,
            },
            {
              time_epoch: 1676007000,
              time: "2023-02-10 11:00",
              temp_c: 24.9,
              temp_f: 76.8,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 159,
              wind_dir: "SSE",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 31,
              cloud: 5,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 24.9,
              windchill_f: 76.8,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.9,
              gust_kph: 11.2,
              uv: 6,
            },
            {
              time_epoch: 1676010600,
              time: "2023-02-10 12:00",
              temp_c: 28.9,
              temp_f: 84,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 153,
              wind_dir: "SSE",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 29,
              cloud: 5,
              feelslike_c: 27.6,
              feelslike_f: 81.7,
              windchill_c: 28.9,
              windchill_f: 84,
              heatindex_c: 27.6,
              heatindex_f: 81.7,
              dewpoint_c: 8.9,
              dewpoint_f: 48,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.3,
              gust_kph: 10.1,
              uv: 7,
            },
            {
              time_epoch: 1676014200,
              time: "2023-02-10 13:00",
              temp_c: 30,
              temp_f: 86,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 157,
              wind_dir: "SSE",
              pressure_mb: 1011,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 27,
              cloud: 3,
              feelslike_c: 28.6,
              feelslike_f: 83.5,
              windchill_c: 30,
              windchill_f: 86,
              heatindex_c: 28.6,
              heatindex_f: 83.5,
              dewpoint_c: 9.2,
              dewpoint_f: 48.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.8,
              gust_kph: 9.4,
              uv: 8,
            },
            {
              time_epoch: 1676017800,
              time: "2023-02-10 14:00",
              temp_c: 30.6,
              temp_f: 87.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 173,
              wind_dir: "S",
              pressure_mb: 1010,
              pressure_in: 29.81,
              precip_mm: 0,
              precip_in: 0,
              humidity: 27,
              cloud: 2,
              feelslike_c: 29.2,
              feelslike_f: 84.6,
              windchill_c: 30.6,
              windchill_f: 87.1,
              heatindex_c: 29.2,
              heatindex_f: 84.6,
              dewpoint_c: 9.6,
              dewpoint_f: 49.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 8,
            },
            {
              time_epoch: 1676021400,
              time: "2023-02-10 15:00",
              temp_c: 30.7,
              temp_f: 87.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 188,
              wind_dir: "S",
              pressure_mb: 1009,
              pressure_in: 29.79,
              precip_mm: 0,
              precip_in: 0,
              humidity: 28,
              cloud: 3,
              feelslike_c: 29.4,
              feelslike_f: 84.9,
              windchill_c: 30.7,
              windchill_f: 87.3,
              heatindex_c: 29.4,
              heatindex_f: 84.9,
              dewpoint_c: 10.1,
              dewpoint_f: 50.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.4,
              gust_kph: 8.6,
              uv: 8,
            },
            {
              time_epoch: 1676025000,
              time: "2023-02-10 16:00",
              temp_c: 30.4,
              temp_f: 86.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 207,
              wind_dir: "SSW",
              pressure_mb: 1009,
              pressure_in: 29.78,
              precip_mm: 0,
              precip_in: 0,
              humidity: 31,
              cloud: 4,
              feelslike_c: 29.5,
              feelslike_f: 85.1,
              windchill_c: 30.4,
              windchill_f: 86.7,
              heatindex_c: 29.5,
              heatindex_f: 85.1,
              dewpoint_c: 11.6,
              dewpoint_f: 52.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.5,
              gust_kph: 7.2,
              uv: 8,
            },
            {
              time_epoch: 1676028600,
              time: "2023-02-10 17:00",
              temp_c: 27.5,
              temp_f: 81.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 0.4,
              wind_kph: 0.7,
              wind_degree: 226,
              wind_dir: "SW",
              pressure_mb: 1009,
              pressure_in: 29.78,
              precip_mm: 0,
              precip_in: 0,
              humidity: 37,
              cloud: 3,
              feelslike_c: 27.1,
              feelslike_f: 80.8,
              windchill_c: 27.5,
              windchill_f: 81.5,
              heatindex_c: 27.1,
              heatindex_f: 80.8,
              dewpoint_c: 11.7,
              dewpoint_f: 53.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 0.4,
              gust_kph: 0.7,
              uv: 7,
            },
            {
              time_epoch: 1676032200,
              time: "2023-02-10 18:00",
              temp_c: 25.6,
              temp_f: 78.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 83,
              wind_dir: "E",
              pressure_mb: 1009,
              pressure_in: 29.79,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 4,
              feelslike_c: 25.7,
              feelslike_f: 78.3,
              windchill_c: 25.6,
              windchill_f: 78.1,
              heatindex_c: 25.7,
              heatindex_f: 78.3,
              dewpoint_c: 10.6,
              dewpoint_f: 51.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.3,
              gust_kph: 6.8,
              uv: 1,
            },
            {
              time_epoch: 1676035800,
              time: "2023-02-10 19:00",
              temp_c: 24.4,
              temp_f: 75.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 101,
              wind_dir: "ESE",
              pressure_mb: 1010,
              pressure_in: 29.81,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 4,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 24.4,
              windchill_f: 75.9,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 10.2,
              dewpoint_f: 50.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 1,
            },
            {
              time_epoch: 1676039400,
              time: "2023-02-10 20:00",
              temp_c: 21.9,
              temp_f: 71.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 128,
              wind_dir: "SE",
              pressure_mb: 1010,
              pressure_in: 29.84,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 4,
              feelslike_c: 21.9,
              feelslike_f: 71.4,
              windchill_c: 21.9,
              windchill_f: 71.4,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1676043000,
              time: "2023-02-10 21:00",
              temp_c: 21.3,
              temp_f: 70.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 168,
              wind_dir: "SSE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 45,
              cloud: 5,
              feelslike_c: 21.3,
              feelslike_f: 70.3,
              windchill_c: 21.3,
              windchill_f: 70.3,
              heatindex_c: 24.1,
              heatindex_f: 75.4,
              dewpoint_c: 8.8,
              dewpoint_f: 47.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1,
            },
            {
              time_epoch: 1676046600,
              time: "2023-02-10 22:00",
              temp_c: 20.7,
              temp_f: 69.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 166,
              wind_dir: "SSE",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 47,
              cloud: 5,
              feelslike_c: 20.7,
              feelslike_f: 69.3,
              windchill_c: 20.7,
              windchill_f: 69.3,
              heatindex_c: 20.7,
              heatindex_f: 69.3,
              dewpoint_c: 8.9,
              dewpoint_f: 48,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.5,
              gust_kph: 13.7,
              uv: 1,
            },
            {
              time_epoch: 1676050200,
              time: "2023-02-10 23:00",
              temp_c: 20.2,
              temp_f: 68.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.7,
              wind_kph: 4.3,
              wind_degree: 182,
              wind_dir: "S",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 48,
              cloud: 5,
              feelslike_c: 20.2,
              feelslike_f: 68.4,
              windchill_c: 20.2,
              windchill_f: 68.4,
              heatindex_c: 20.2,
              heatindex_f: 68.4,
              dewpoint_c: 8.9,
              dewpoint_f: 48,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 5.6,
              gust_kph: 9,
              uv: 1,
            },
          ],
        },
        {
          date: "2023-02-11",
          date_epoch: 1676073600,
          day: {
            maxtemp_c: 29.5,
            maxtemp_f: 85.1,
            mintemp_c: 15.5,
            mintemp_f: 59.9,
            avgtemp_c: 21.1,
            avgtemp_f: 70.1,
            maxwind_mph: 9.2,
            maxwind_kph: 14.8,
            totalprecip_mm: 0,
            totalprecip_in: 0,
            totalsnow_cm: 0,
            avgvis_km: 10,
            avgvis_miles: 6,
            avghumidity: 43,
            daily_will_it_rain: 0,
            daily_chance_of_rain: 0,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            uv: 6,
          },
          astro: {
            sunrise: "07:04 AM",
            sunset: "06:08 PM",
            moonrise: "11:11 PM",
            moonset: "10:06 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: "76",
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1676053800,
              time: "2023-02-11 00:00",
              temp_c: 19.4,
              temp_f: 66.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 2.2,
              wind_kph: 3.6,
              wind_degree: 202,
              wind_dir: "SSW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 4,
              feelslike_c: 19.4,
              feelslike_f: 66.9,
              windchill_c: 19.4,
              windchill_f: 66.9,
              heatindex_c: 19.4,
              heatindex_f: 66.9,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 4.7,
              gust_kph: 7.6,
              uv: 1,
            },
            {
              time_epoch: 1676057400,
              time: "2023-02-11 01:00",
              temp_c: 18.9,
              temp_f: 66,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 240,
              wind_dir: "WSW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 50,
              cloud: 6,
              feelslike_c: 18.9,
              feelslike_f: 66,
              windchill_c: 18.9,
              windchill_f: 66,
              heatindex_c: 18.9,
              heatindex_f: 66,
              dewpoint_c: 8.3,
              dewpoint_f: 46.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1,
            },
            {
              time_epoch: 1676061000,
              time: "2023-02-11 02:00",
              temp_c: 18.2,
              temp_f: 64.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 264,
              wind_dir: "W",
              pressure_mb: 1011,
              pressure_in: 29.86,
              precip_mm: 0,
              precip_in: 0,
              humidity: 51,
              cloud: 3,
              feelslike_c: 18.2,
              feelslike_f: 64.8,
              windchill_c: 18.2,
              windchill_f: 64.8,
              heatindex_c: 18.2,
              heatindex_f: 64.8,
              dewpoint_c: 8,
              dewpoint_f: 46.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.2,
              gust_kph: 18,
              uv: 1,
            },
            {
              time_epoch: 1676064600,
              time: "2023-02-11 03:00",
              temp_c: 17.4,
              temp_f: 63.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 280,
              wind_dir: "W",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 0,
              feelslike_c: 17.4,
              feelslike_f: 63.3,
              windchill_c: 17.4,
              windchill_f: 63.3,
              heatindex_c: 17.4,
              heatindex_f: 63.3,
              dewpoint_c: 7.8,
              dewpoint_f: 46,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1676068200,
              time: "2023-02-11 04:00",
              temp_c: 16.7,
              temp_f: 62.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 300,
              wind_dir: "WNW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 3,
              feelslike_c: 16.7,
              feelslike_f: 62.1,
              windchill_c: 16.7,
              windchill_f: 62.1,
              heatindex_c: 16.7,
              heatindex_f: 62.1,
              dewpoint_c: 7.4,
              dewpoint_f: 45.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1676071800,
              time: "2023-02-11 05:00",
              temp_c: 16.1,
              temp_f: 61,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 301,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 4,
              feelslike_c: 16.1,
              feelslike_f: 61,
              windchill_c: 16.1,
              windchill_f: 61,
              heatindex_c: 16.1,
              heatindex_f: 61,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.7,
              gust_kph: 17.3,
              uv: 1,
            },
            {
              time_epoch: 1676075400,
              time: "2023-02-11 06:00",
              temp_c: 15.6,
              temp_f: 60.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 297,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.89,
              precip_mm: 0,
              precip_in: 0,
              humidity: 54,
              cloud: 5,
              feelslike_c: 15.6,
              feelslike_f: 60.1,
              windchill_c: 15.6,
              windchill_f: 60.1,
              heatindex_c: 15.6,
              heatindex_f: 60.1,
              dewpoint_c: 6.3,
              dewpoint_f: 43.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 1,
            },
            {
              time_epoch: 1676079000,
              time: "2023-02-11 07:00",
              temp_c: 15.5,
              temp_f: 59.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 294,
              wind_dir: "WNW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 53,
              cloud: 1,
              feelslike_c: 15.5,
              feelslike_f: 59.9,
              windchill_c: 15.5,
              windchill_f: 59.9,
              heatindex_c: 15.5,
              heatindex_f: 59.9,
              dewpoint_c: 5.9,
              dewpoint_f: 42.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 5,
            },
            {
              time_epoch: 1676082600,
              time: "2023-02-11 08:00",
              temp_c: 16.9,
              temp_f: 62.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 287,
              wind_dir: "WNW",
              pressure_mb: 1014,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 49,
              cloud: 0,
              feelslike_c: 16.9,
              feelslike_f: 62.4,
              windchill_c: 16.9,
              windchill_f: 62.4,
              heatindex_c: 16.9,
              heatindex_f: 62.4,
              dewpoint_c: 6,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14,
              uv: 5,
            },
            {
              time_epoch: 1676086200,
              time: "2023-02-11 09:00",
              temp_c: 19.3,
              temp_f: 66.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 283,
              wind_dir: "WNW",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 3,
              feelslike_c: 19.3,
              feelslike_f: 66.7,
              windchill_c: 19.3,
              windchill_f: 66.7,
              heatindex_c: 19.3,
              heatindex_f: 66.7,
              dewpoint_c: 6,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 5,
            },
            {
              time_epoch: 1676089800,
              time: "2023-02-11 10:00",
              temp_c: 21.5,
              temp_f: 70.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 290,
              wind_dir: "WNW",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 40,
              cloud: 1,
              feelslike_c: 21.5,
              feelslike_f: 70.7,
              windchill_c: 21.5,
              windchill_f: 70.7,
              heatindex_c: 23.9,
              heatindex_f: 75,
              dewpoint_c: 7.3,
              dewpoint_f: 45.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 6,
            },
            {
              time_epoch: 1676093400,
              time: "2023-02-11 11:00",
              temp_c: 23.6,
              temp_f: 74.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 293,
              wind_dir: "WNW",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 3,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 23.6,
              windchill_f: 74.5,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 8.9,
              dewpoint_f: 48,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 6,
            },
            {
              time_epoch: 1676097000,
              time: "2023-02-11 12:00",
              temp_c: 25.3,
              temp_f: 77.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 296,
              wind_dir: "WNW",
              pressure_mb: 1014,
              pressure_in: 29.96,
              precip_mm: 0,
              precip_in: 0,
              humidity: 36,
              cloud: 1,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 25.3,
              windchill_f: 77.5,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 9.3,
              dewpoint_f: 48.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 7,
            },
            {
              time_epoch: 1676100600,
              time: "2023-02-11 13:00",
              temp_c: 26.6,
              temp_f: 79.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 9.2,
              wind_kph: 14.8,
              wind_degree: 296,
              wind_dir: "WNW",
              pressure_mb: 1013,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 1,
              feelslike_c: 26.1,
              feelslike_f: 79,
              windchill_c: 26.6,
              windchill_f: 79.9,
              heatindex_c: 26.1,
              heatindex_f: 79,
              dewpoint_c: 9.4,
              dewpoint_f: 48.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 7,
            },
            {
              time_epoch: 1676104200,
              time: "2023-02-11 14:00",
              temp_c: 29.5,
              temp_f: 85.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 32,
              cloud: 0,
              feelslike_c: 28.6,
              feelslike_f: 83.5,
              windchill_c: 29.5,
              windchill_f: 85.1,
              heatindex_c: 28.6,
              heatindex_f: 83.5,
              dewpoint_c: 11.1,
              dewpoint_f: 52,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.1,
              gust_kph: 16.2,
              uv: 7,
            },
            {
              time_epoch: 1676107800,
              time: "2023-02-11 15:00",
              temp_c: 29.5,
              temp_f: 85.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 304,
              wind_dir: "NW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 28.5,
              feelslike_f: 83.3,
              windchill_c: 29.5,
              windchill_f: 85.1,
              heatindex_c: 28.5,
              heatindex_f: 83.3,
              dewpoint_c: 10.7,
              dewpoint_f: 51.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.9,
              gust_kph: 14.4,
              uv: 7,
            },
            {
              time_epoch: 1676111400,
              time: "2023-02-11 16:00",
              temp_c: 28.9,
              temp_f: 84,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 34,
              cloud: 0,
              feelslike_c: 28.2,
              feelslike_f: 82.8,
              windchill_c: 28.9,
              windchill_f: 84,
              heatindex_c: 28.2,
              heatindex_f: 82.8,
              dewpoint_c: 11.5,
              dewpoint_f: 52.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 7,
            },
            {
              time_epoch: 1676115000,
              time: "2023-02-11 17:00",
              temp_c: 25.7,
              temp_f: 78.3,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 302,
              wind_dir: "WNW",
              pressure_mb: 1012,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 41,
              cloud: 0,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 25.7,
              windchill_f: 78.3,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 11.5,
              dewpoint_f: 52.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.7,
              gust_kph: 14,
              uv: 7,
            },
            {
              time_epoch: 1676118600,
              time: "2023-02-11 18:00",
              temp_c: 24.3,
              temp_f: 75.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 306,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 24.3,
              windchill_f: 75.7,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 11.9,
              dewpoint_f: 53.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.3,
              gust_kph: 13.3,
              uv: 1,
            },
            {
              time_epoch: 1676122200,
              time: "2023-02-11 19:00",
              temp_c: 23.5,
              temp_f: 74.3,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 5.1,
              wind_kph: 8.3,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 46,
              cloud: 0,
              feelslike_c: 24.8,
              feelslike_f: 76.6,
              windchill_c: 23.5,
              windchill_f: 74.3,
              heatindex_c: 24.8,
              heatindex_f: 76.6,
              dewpoint_c: 11.3,
              dewpoint_f: 52.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 1,
            },
            {
              time_epoch: 1676125800,
              time: "2023-02-11 20:00",
              temp_c: 20.1,
              temp_f: 68.2,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 4.5,
              wind_kph: 7.2,
              wind_degree: 305,
              wind_dir: "NW",
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              humidity: 42,
              cloud: 2,
              feelslike_c: 20.1,
              feelslike_f: 68.2,
              windchill_c: 20.1,
              windchill_f: 68.2,
              heatindex_c: 20.1,
              heatindex_f: 68.2,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 1,
            },
            {
              time_epoch: 1676129400,
              time: "2023-02-11 21:00",
              temp_c: 19.3,
              temp_f: 66.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 297,
              wind_dir: "WNW",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 3,
              feelslike_c: 19.3,
              feelslike_f: 66.7,
              windchill_c: 19.3,
              windchill_f: 66.7,
              heatindex_c: 19.3,
              heatindex_f: 66.7,
              dewpoint_c: 5.1,
              dewpoint_f: 41.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 1,
            },
            {
              time_epoch: 1676133000,
              time: "2023-02-11 22:00",
              temp_c: 18.2,
              temp_f: 64.8,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 39,
              cloud: 0,
              feelslike_c: 18.2,
              feelslike_f: 64.8,
              windchill_c: 18.2,
              windchill_f: 64.8,
              heatindex_c: 18.2,
              heatindex_f: 64.8,
              dewpoint_c: 3.9,
              dewpoint_f: 39,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.2,
              gust_kph: 27.7,
              uv: 1,
            },
            {
              time_epoch: 1676136600,
              time: "2023-02-11 23:00",
              temp_c: 17.5,
              temp_f: 63.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 321,
              wind_dir: "NW",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0,
              precip_in: 0,
              humidity: 31,
              cloud: 0,
              feelslike_c: 17.5,
              feelslike_f: 63.5,
              windchill_c: 17.5,
              windchill_f: 63.5,
              heatindex_c: 17.5,
              heatindex_f: 63.5,
              dewpoint_c: 0.1,
              dewpoint_f: 32.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.2,
              gust_kph: 27.7,
              uv: 1,
            },
          ],
        },
      ],
    },
  },
  loading: false,
  error: null,
};

export function CurrWeatherProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  // const currWeather = useCurrentWeather();
  return (
    <CurrWeatherContext.Provider value={currWeather}>
      {children}
    </CurrWeatherContext.Provider>
  );
}
